### ISSUE TITLE
[Bug]: Dedicated Server Crash with latest update (1.3)

### ISSUE THREAD

**Issue by HockeyZman2000** [someaddons/FastAsyncWorldSave#1]
### Describe the bug you're experiencing

I'm regularly getting a crash when the server attempts to save asynchronously, mentioning "invalid null NBT values". This did not occur on the previous version.

### Reproducability

1. Launch dedicated server.
2. Join into the world.
3. Server should crash after a few minutes.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/HockeyZman2000/110e2443488f629be480819dd45ff6d4

**Comment by lanwoodall423** [comment]
[latest.log](https://github.com/someaddons/FastAsyncWorldSave/files/13888186/latest.log)
[crash-2024-01-10_08.14.48-server.txt](https://github.com/someaddons/FastAsyncWorldSave/files/13888187/crash-2024-01-10_08.14.48-server.txt)
Same issue on singleplayer client. Crash on world load

**Comment by someaddons** [comment]
fixed^^
