### ISSUE TITLE
[Bug]: Possible crash with DomesticationInnovation

### ISSUE THREAD

**Issue by MaxWasUnavailable** [someaddons/FastAsyncWorldSave#11]
### Describe the bug you're experiencing

Server crash. Possibly unrelated, but FastAsyncWorldSave was mentioned in the stacktrace.

### Reproducability

Unable to reliably reproduce, but has happened a couple of times.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://pastebin.com/yYXccGYM

**Comment by someaddons** [comment]
ye thats the domesticationinnovation mod failing to save its data, should report it to them :)
I can add a crash prevention and log it instead
