### ISSUE TITLE
[Question]Comparison with Smooth Chunk Save in a client environment

### ISSUE THREAD

**Issue by QianFuv** [someaddons/FastAsyncWorldSave#12]
Are these two mods implementing different optimization methods for the same issue? Which one would perform better in a client-side environment?

**Comment by someaddons** [comment]
they optimize very different things, smooth chunk saves saves chunks, this saves extra data of mods alongside the world.
If you play singleplayer they have an effect, but on client side while playing on the server they do nothing, as they are about the serverside(singleplayer also runs a server)
