### ISSUE TITLE
[1.20.4] Asking for updates to NeoForge 1.20.4

### ISSUE THREAD

**Issue by TheSnowyChickens** [someaddons/FastAsyncWorldSave#13]
Hello,
I know 1.20.4 is meanwhile outdated, but there are some great packs on this version with problems. (and Actually Additions)

Example: In Equivalent Exchange 4 are some saving problems with a to high SSD utilization (like no SSD can handle those traffic with 2 players online on a server), every 6 minutes there is a strong overload from Minecraft, because MC can't handle the save.

Our server owner and friends tried to figureout the problems and tried to fix it with some mods and setting changes, but nothing worked.
Then we found your mod which is not on .4, so we tried our luck with the 1.20.1 version and 1.21 version but nope.
Even """updating""" it on our self to .4 NeoForge brought no positive experience. (we don't have active Java develops)

After some time, there are only 2 options left: EEX4 fix it (but this can take far to long) or we ask you, if you are so friendly to update your mods to 1.20.4. :D

The pack contains 272 mods, on NeoForge 20.4.237.

❤️

**Comment by someaddons** [comment]
Sorry but 20.4 is quite dead, dont have the time to port to all versions 😅
