### ISSUE TITLE
[Bug]: Invalid null NBT value with key data

### ISSUE THREAD

**Issue by DeshiDesu** [someaddons/FastAsyncWorldSave#2]
### Describe the bug you're experiencing

Related to this issue here: https://github.com/someaddons/FastAsyncWorldSave/issues/1
After loading my singleplayer world it instantly crashes.

### Reproducability

Install fastasyncworldsave-1.20.1-1.4.jar

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/DeshiDesu/f29440c27473d4db59b73f0228a09ffc

**Comment by someaddons** [comment]
you're running version 1.3 in that log, probably did not delete/update the version properly^^

**Comment by DeshiDesu** [comment]
My apologies... thanks for pointing that out for me.
