### ISSUE TITLE
[Bug]: Multiblock structure content and functionality, including sophisticated backpack content issue after latest updated. Mc 1.20.1. Mod version: 1.6

### ISSUE THREAD

**Issue by DigitalWendigo** [someaddons/FastAsyncWorldSave#3]
### Describe the bug you're experiencing

So I recently updated the mod while using Prism Launcher, and the update log mentioned that it would fix the world being saved incorrectly. 
However, unfortunately enough in my case, the world saved just fine before this update, and only after updating it to 1.6, did I start experiencing the exact issue it said to fix. 
Upon saving my progress yesterday (After having updated mod to 1.6 and letting it afk for half a day), I booted up the game this morning to let it afk again while I go work, but upon entering the world, I was met with every multiblock structure having failed to load its contents, and failing to function. 
Thankfully I set up safety measures for the reactors, so nothing exploded, but saw that neither the water, steam, fuel or any other content was correctly saved. 
I then checked my backpack to take some tools out of it and try to fix the issue, only to notice that all my backpacks were cleared of their content. 

I have since reverted back to 1.4, and this seems to have fixed the issue. 
I doubt it is the fault of the other aforementioned bods, since I have not updated those in almost a week now, with Mekanism not having recieved an update in the last two months. 

If more information is needed, let me know. 

### Reproducability

Update to Mod version 1.6, and save a world containing (in my case) a Mekanism multiblock structure. 
Additionally, have sophisticated backpacks installed and observe the contents of both aforementioned things being cleared upon reloading the world. 
- This did not happen with previous versions. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/DigitalWendigo/c3471db70d4e895fe027d0f67f034cc6

**Comment by someaddons** [comment]
are you able to reproduce this with version 1.6? (using a world copy)
I just tried both backpacks & mekanism multiblocks and they worked fine, maybe you had updated to version 1.5 before which had issues?
update: managed to reproduce with mekanism

**Comment by someaddons** [comment]
fixed in 1.7^^

**Comment by DigitalWendigo** [comment]
Fantastic! 
Thanks a bunch!
