### ISSUE TITLE
[Bug]: fastasyncworldsave-1.20.1-1.7.jar crash 1.20.1 minecraft forge java 17

### ISSUE THREAD

**Issue by vnsmnn** [someaddons/FastAsyncWorldSave#4]
### Describe the bug you're experiencing

Hi, my server always crashes whenever I add this mod. After removing this mod, it doesn't happen anymore.

### Reproducability

whenever I add this mod in my modpack the game crash between 30min to 1 hour

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/vnsmnn/8f621d1c04003dc989c665a79c9feca2

**Comment by someaddons** [comment]
thats just lithium crashing on a very unrelated codepath, aka something this mod doesnt touch at all. Report to lithium
