### ISSUE TITLE
[Bug]: Crashes with Valkyrien Skies 2 on Fabric 1.20.1

### ISSUE THREAD

**Issue by goodiesohhi** [someaddons/FastAsyncWorldSave#5]
### Describe the bug you're experiencing

Doesn't crash at first, however it causes vs2 ship data to not save properly or something because after running the server with both vs2 and fastasyncworldsave, vs2 will crash the server upon server start with "unable to find serialized ship data" and this forces you to delete the vs ship data file and after the server will start but if the server is running with both mods, it will simply repeat.
I tested both with this mod and without and it is what's causing this crash

### Reproducability

Have VS2, Have this mod.
Start server.
Close server.
Start server again (crashes for me)

### Mod up to date

- [ ] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/goodiesohhi/fb82d9c442aa1ca781f6bdf49a1335aa

**Comment by someaddons** [comment]
yea version 1.5 has a bug which is why its no longer available and the latest version is 1.7
