### ISSUE TITLE
[Bug] [1.20.1]: Could Not Save Data

### ISSUE THREAD

**Issue by Sandriell** [someaddons/FastAsyncWorldSave#6]
### Describe the bug you're experiencing

Updated to the latest version (fastasyncworldsave-1.20.1-1.8) and now the world is falling to save properly.

**Relevant Error**: https://gist.github.com/Sandriell/15d313d3dbeb2e258e5456eab387b3e8

Full log below incase it could help.

### Reproducability

Try to save in single player. Unknown if it affects dedicated server.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/Sandriell/c3c6c2778c1487f1e07ec0667062eefa

**Comment by someaddons** [comment]
fixed in 1.9, lootr is using subfolder which vanilla normally does not support so it was failing
