### ISSUE TITLE
[Bug] [1.20.1]: Mixin Failed to Apply

### ISSUE THREAD

**Issue by Sandriell** [someaddons/FastAsyncWorldSave#7]
### Describe the bug you're experiencing

Seeing the following error during world loading- single player.

**Relevant Error**: https://gist.github.com/Sandriell/c0e5fd18b83815bd6866690eea01e06f

**Full Log**: https://gist.github.com/Sandriell/f6a1cc50ce6d6a2f5a797ee8ad9c8008

**Mod**: fastasyncworldsave-1.20.1-1.9

### Reproducability

Load single player world.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/Sandriell/c0e5fd18b83815bd6866690eea01e06f

**Comment by someaddons** [comment]
fixed in 2.0, compiling randomly forgot to include the refmap
