### ISSUE TITLE
[Question] Compatibility with Smooth Chunk Save

### ISSUE THREAD

**Issue by pixel96x** [someaddons/FastAsyncWorldSave#8]
Is this mod compatible with [Smooth Chunk Save](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)?
If so, does using both of them would give better performance, or only one of them should be installed at the same time?

**Comment by someaddons** [comment]
yes it is, smoothchunk save takes care of chunk saving, while this mod takes care of world saved data(the files found within the /data folder in a world) so they very much work side by side, each yielding their benefit
