### ISSUE TITLE
[Bug]: Mekanism QIO fails to save it's qio_type_cache.dat

### ISSUE THREAD

**Issue by KostromDan** [someaddons/FastAsyncWorldSave#9]
### Describe the bug you're experiencing

Fast Async World Save blocks renaming `qio_type_cache.dat.temp` to `qio_type_cache.dat` what's why QIO makanism storage wipes all it's contents after rejoining the world.
```java
[Server thread/ERROR] [mekanism.common.Mekanism/]: Failed to rename qio_type_cache.dat.temp
```

### Reproducability

modlist:
![image](https://github.com/someaddons/FastAsyncWorldSave/assets/90044015/247f117d-2ed9-43ef-a498-af395a72b4b2)

1. Build QIO storage.
![2024-05-24_18 47 18](https://github.com/someaddons/FastAsyncWorldSave/assets/90044015/d4586e86-2d35-40db-b8e8-5c1b2adede9d)
![2024-05-24_18 47 26](https://github.com/someaddons/FastAsyncWorldSave/assets/90044015/eea26988-705b-4cfd-bc55-0d33bc316661)

2. Link it.
![2024-05-24_18 47 30](https://github.com/someaddons/FastAsyncWorldSave/assets/90044015/2f39d448-14e2-466d-bf12-9d7a71bb172f)

3. Put item into it.
![2024-05-24_18 47 33](https://github.com/someaddons/FastAsyncWorldSave/assets/90044015/e3670eb0-5a8b-4d5c-a29a-6c9ec569b24f)

4. Rejoin world. All items wiped.
![2024-05-24_18 47 54](https://github.com/someaddons/FastAsyncWorldSave/assets/90044015/dbd3f70d-3e2c-40c5-9d80-6629bfa47368)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/KostromDan/c4127b55bd6ed2337559659ba1ac652d

**Comment by someaddons** [comment]
fixed in 2.0
